name: BigDL Build Portable Zip

on:
  pull_request:
    branches: [ main ]
    # paths:
    #   - 'python/llm/portable-zip/**'
  workflow_dispatch:


jobs:
  build-cpython:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
      - uses: actions/checkout@v4
        with:
          repository: 'python/cpython'
          ref: '3.9'
      - name: Build cpython
        run: |
          cd Tools/msi
          ./buildrelease.bat -x64 --skip-doc --skip-nuget --skip-msi
  